
# COURS
FROM python:3.9-alpine
COPY ./app.py /app/
CMD python /app/app.py

# CHATGPT
# Utilise Python 3.9 comme image de base
# FROM python:3.9

# Définit le répertoire de travail à l'intérieur du conteneur
# WORKDIR /app

# Copie les fichiers locaux dans le conteneur
# COPY . /app

# Installe les dépendances
# RUN pip install -r requirements.txt

# Spécifie la commande à exécuter au démarrage du conteneur
# CMD ["python", "app.py"]
